# **Challenge #1: Working with Tensors in TensorFlow**
### **Topic**: Understanding TensorFlow’s Tensor Structure, Data Types, and Operations

### **Problem Description**:
TensorFlow uses **tensors** as its core data structure, similar to multi-dimensional arrays. Your task is to:

1. **Create tensors** using:
   - `tf.constant`
   - `tf.Variable`
   - `tf.convert_to_tensor`
   
2. **Perform basic tensor operations**, including:
   - Element-wise addition, multiplication
   - Broadcasting with scalars
   - Reshaping
   - Transposing

3. **Modify mutable tensors** using `tf.Variable`.

4. **Convert tensors to NumPy arrays** and vice versa.

### **Constraints**:
- Use TensorFlow functions only (`tf.constant`, `tf.Variable`, `tf.convert_to_tensor`).
- Ensure all tensors are of type `float32`.
- Do **not** use NumPy for operations (except for conversion tasks).

---

### **Example Input & Output**

#### **Example 1: Creating Tensors**
##### **Input**
```python
# Given the following list:
data = [[1, 2, 3], [4, 5, 6]]

# Convert it to a tensor using TensorFlow.
```
##### **Expected Output**
```
Tensor representation of data
Shape: (2, 3)
Data Type: float32
```

---

#### **Example 2: Tensor Operations**
##### **Input**
```python
# Given these two tensors:
tensorA = [[1, 2], [3, 4]]
tensorB = [[5, 6], [7, 8]]

# Perform element-wise addition and multiplication.
```
##### **Expected Output**
```
Sum Tensor:
[[ 6.  8.]
 [10. 12.]]

Product Tensor:
[[ 5. 12.]
 [21. 32.]]
```

---

#### **Example 3: Broadcasting**
##### **Input**
```python
# Given this tensor:
tensor = [[1, 2], [3, 4]]

# Multiply the tensor by a scalar (2.0).
```
##### **Expected Output**
```
Resulting Tensor:
[[ 2.  4.]
 [ 6.  8.]]
```

---

#### **Example 4: Reshaping and Transposing**
##### **Input**
```python
# Given this tensor:
tensor = [[1, 2, 3], [4, 5, 6]]

# Reshape it into shape (3,2) and transpose it.
```
##### **Expected Output**
```
Reshaped Tensor:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Transposed Tensor:
[[1. 4.]
 [2. 5.]
 [3. 6.]]
```

---

### **Hints**:
- Use `tf.convert_to_tensor()` to transform Python lists into tensors.
- Use `tf.add()` and `tf.multiply()` for element-wise operations.
- Use `tf.reshape()` to change the shape of a tensor.
- Use `tf.transpose()` to swap dimensions.

---

# Solution

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 1. Creating Tensors

# Create a tensor using tf.constant
tensor1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=tf.float32)
print("Tensor 1:\n", tensor1)

# Convert a list to a tensor using tf.convert_to_tensor
data = [[1, 2, 3], [4, 5, 6]]
tensor2 = tf.convert_to_tensor(data, dtype=tf.float32)
print("Tensor 2 (converted from list):\n", tensor2)

# Create a mutable tensor using tf.Variable
tensor3 = tf.Variable([[9.0, 10.0], [11.0, 12.0]], dtype=tf.float32)
print("Tensor 3 (mutable):\n", tensor3)

Tensor 1:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Tensor 2 (converted from list):
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Tensor 3 (mutable):
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 9., 10.],
       [11., 12.]], dtype=float32)>


In [3]:
# 2. Modifying Tensors
# Modify tensor3 by adding a constant value
tensor3.assign_add([[1.0, 1.0], [1.0, 1.0]])
print("Updated tensor3:\n", tensor3.numpy())  
# Expected Output: [[10. 11.] [12. 13.]]

Updated tensor3:
 [[10. 11.]
 [12. 13.]]


In [4]:
# 3. Basic Tensor Operations

# Define two tensors
tensorA = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensorB = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Element-wise addition
tensor_sum = tf.add(tensorA, tensorB)
print("Element-wise Addition:\n", tensor_sum.numpy())  
# Expected Output: [[ 6.  8.] [10. 12.]]

# Element-wise multiplication
tensor_product = tf.multiply(tensorA, tensorB)
print("Element-wise Multiplication:\n", tensor_product.numpy())  
# Expected Output: [[ 5. 12.] [21. 32.]]

Element-wise Addition:
 [[ 6.  8.]
 [10. 12.]]
Element-wise Multiplication:
 [[ 5. 12.]
 [21. 32.]]


In [5]:
# 4. Broadcasting Example
scalar = tf.constant(2.0, dtype=tf.float32)
broadcasted_tensor = tensorA * scalar
print("Broadcasting Example:\n", broadcasted_tensor.numpy())  
# Expected Output: [[ 2.  4.] [ 6.  8.]]

Broadcasting Example:
 [[2. 4.]
 [6. 8.]]


In [6]:
# 5. Reshaping and Transposing

# Define a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

# Reshape the tensor
reshaped = tf.reshape(tensor, (3, 2))
print("Reshaped Tensor:\n", reshaped.numpy())  
# Expected Output: [[1. 2.] [3. 4.] [5. 6.]]

# Transpose the tensor
transposed = tf.transpose(tensor)
print("Transposed Tensor:\n", transposed.numpy())  
# Expected Output: [[1. 4.] [2. 5.] [3. 6.]]


Reshaped Tensor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
Transposed Tensor:
 [[1. 4.]
 [2. 5.]
 [3. 6.]]


In [7]:
# 6. Converting between TensorFlow Tensors and NumPy

# Convert a TensorFlow tensor to a NumPy array
numpy_array = tensor.numpy()
print("Tensor to NumPy:\n", numpy_array)

# Convert a NumPy array to a TensorFlow tensor
tensor_from_numpy = tf.convert_to_tensor(numpy_array, dtype=tf.float32)
print("NumPy to TensorFlow Tensor:\n", tensor_from_numpy.numpy())

Tensor to NumPy:
 [[1. 2. 3.]
 [4. 5. 6.]]
NumPy to TensorFlow Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]


---

## **Explanation of the Solution**
1. **Creating Tensors**
   - Used `tf.constant` for immutable tensors.
   - Used `tf.convert_to_tensor` to convert lists into tensors.
   - Used `tf.Variable` for mutable tensors.

2. **Modifying a `tf.Variable` Tensor**
   - Used `.assign_add()` to modify a tensor.

3. **Basic Tensor Operations**
   - Used `tf.add()` and `tf.multiply()` for element-wise operations.
   - Demonstrated broadcasting by multiplying a tensor by a scalar.

4. **Reshaping and Transposing**
   - Used `tf.reshape()` to modify tensor shape.
   - Used `tf.transpose()` to swap axes.

5. **TensorFlow and NumPy Interoperability**
   - Used `.numpy()` to convert a TensorFlow tensor to a NumPy array.
   - Used `tf.convert_to_tensor()` to convert a NumPy array back to a TensorFlow tensor.

---

## **Time Complexity Analysis**
- **Creating tensors (`tf.constant`, `tf.convert_to_tensor`, `tf.Variable`)** → **O(1)** for each operation.
- **Element-wise operations (`add`, `multiply`)** → **O(n)** where `n` is the number of elements in the tensor.
- **Broadcasting operations** → **O(n)** (optimized within TensorFlow).
- **Reshaping (`tf.reshape`)** → **O(1)** (only modifies metadata, no actual computation).
- **Transposing (`tf.transpose`)** → **O(n)** where `n` is the number of elements.
- **Conversion to/from NumPy (`.numpy()`, `tf.convert_to_tensor`)** → **O(n)** since data is copied.

---

## **Additional Explanation**

In the solution, I used **three different methods** for creating tensors:  
1. **`tf.constant()`**  
2. **`tf.convert_to_tensor()`**  
3. **`tf.Variable()`**  

Each of these serves a distinct purpose:

#### **1. `tf.constant()`**
- Used to create immutable (unchangeable) tensors.
- Once created, the values **cannot** be modified.
- Suitable for defining fixed tensors that do not need to be updated during computation.

##### **Example**
```python
tensor1 = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
```
Once `tensor1` is created, you **cannot modify** its values.

---

#### **2. `tf.convert_to_tensor()`**
- Used to **convert** existing data (lists, NumPy arrays, etc.) into TensorFlow tensors.
- This is useful when working with external datasets that are initially in Python lists or NumPy arrays.

##### **Example**
```python
data = [[1, 2, 3], [4, 5, 6]]
tensor2 = tf.convert_to_tensor(data, dtype=tf.float32)
```
This method is flexible and automatically detects the correct shape and type of the data.

---

#### **3. `tf.Variable()`**
- Unlike `tf.constant()`, `tf.Variable()` **allows modifications**.
- Used when the values of a tensor **need to be updated**, such as during **gradient descent in deep learning models**.

##### **Example**
```python
tensor3 = tf.Variable([[9.0, 10.0], [11.0, 12.0]], dtype=tf.float32)
```
`tensor3` is **mutable**, meaning we can modify its values.

---

### **What is `assign_add()` and Which Part of the Challenge Description Was Related to It?**

#### **What is `assign_add()`?**
- `assign_add()` is a method used with **`tf.Variable`** to modify its values **in-place**.
- It **adds** a given tensor to the current values of the variable.
- It is useful in **machine learning training loops**, where parameters (weights, biases) are updated incrementally.

##### **Example**
```python
tensor3.assign_add([[1.0, 1.0], [1.0, 1.0]])
```
This modifies `tensor3` by adding `[[1.0, 1.0], [1.0, 1.0]]` to its existing values.

---

### **Summary**
| Method               | Mutable? | Use Case |
|----------------------|----------|----------------------------------|
| `tf.constant()`      | ❌ No | Fixed tensors, constants, model inputs |
| `tf.convert_to_tensor()` | ❌ No | Convert lists/NumPy to tensors |
| `tf.Variable()`      | ✅ Yes | Trainable variables, weights, biases |

---