# **Challenge #2: Mastering Tensor Broadcasting in TensorFlow**  
#### **Topic**: Broadcasting – Performing operations on tensors of different shapes.  

---

### **Problem Description**:
Broadcasting allows you to perform arithmetic operations between tensors of **different shapes** without manually reshaping them. Your task is to:

1. **Perform element-wise operations using broadcasting**:  
   - Add a **scalar** to a **2D tensor**.  
   - Multiply a **1D row vector** with a **2D tensor**.  
   - Add a **column vector** to a **2D tensor**.  

2. **Identify an incompatible shape scenario** where broadcasting **fails** and handle it gracefully.  

3. **Use broadcasting to compute the element-wise sum of two tensors without explicitly reshaping them.**  

---

### **Constraints**:
- You **must** use TensorFlow functions for operations (`tf.add()`, `tf.multiply()`, etc.).
- The **resulting tensors should be of type `float32`**.
- Your implementation should **handle cases where broadcasting is not possible** by catching errors.

---

### **Example Input & Output**

#### **Example 1: Adding a Scalar to a 2D Tensor**  
##### **Input**:
```python
# Given this tensor:
tensor = [[1, 2], [3, 4]]

# Add scalar value 5.
```
##### **Expected Output**:
```
Resulting Tensor:
[[ 6.  7.]
 [ 8.  9.]]
```

---

#### **Example 2: Multiplying a 1D Row Vector with a 2D Tensor**  
##### **Input**:
```python
# Given this tensor:
tensor = [[1, 2, 3], [4, 5, 6]]

# Multiply by row vector [2, 3, 4].
```
##### **Expected Output**:
```
Resulting Tensor:
[[ 2.  6. 12.]
 [ 8. 15. 24.]]
```

---

#### **Example 3: Adding a Column Vector to a 2D Tensor**  
##### **Input**:
```python
# Given this tensor:
tensor = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

# Add column vector [[1], [2], [3]].
```
##### **Expected Output**:
```
Resulting Tensor:
[[ 11.  21.  31.]
 [ 42.  52.  62.]
 [ 73.  83.  93.]]
```

---

#### **Example 4: Identifying an Incompatible Shape Scenario**  
##### **Input**:
```python
# Given these tensors:
tensorA = [[1, 2], [3, 4]]
tensorB = [5, 6, 7]

# Try to add them.
```
##### **Expected Output**:
```
Error: Tensors have incompatible shapes for broadcasting.
```

---

### **Hints**:
- Use `tf.add()` for element-wise addition.
- Use `tf.multiply()` for element-wise multiplication.
- If an operation fails due to shape mismatch, **catch the error and print a meaningful message**.

---

Let me know if you need any adjustments before you start solving this challenge! 🚀

# Solution

In [1]:
import tensorflow as tf

In [2]:
# 1. Adding a Scalar to a 2D Tensor
tensor = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
scalar = tf.constant(5.0, dtype=tf.float32)

In [3]:
result = tf.add(tensor, scalar)
print("Adding Scalar to 2D Tensor:\n", result.numpy())

Adding Scalar to 2D Tensor:
 [[6. 7.]
 [8. 9.]]


In [4]:
# 3. Multiplying a 1D Row Vector with a 2D Tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
row_vector = tf.constant([2, 3, 4], dtype=tf.float32)

In [5]:
result = tf.multiply(tensor, row_vector)
print("Multiplying 1D Row Vector with 2D Tensor:\n", result.numpy())

Multiplying 1D Row Vector with 2D Tensor:
 [[ 2.  6. 12.]
 [ 8. 15. 24.]]


In [6]:
# 4. Adding a Column Vector to a 2D Tensor
tensor = tf.constant([[10, 20, 30], [40, 50, 60], [70, 80, 90]], dtype=tf.float32)
column_vector = tf.constant([[1], [2], [3]], dtype=tf.float32)

In [7]:
result = tf.add(tensor, column_vector)
print("Adding Column Vector to 2D Tensor:\n", result.numpy())

Adding Column Vector to 2D Tensor:
 [[11. 21. 31.]
 [42. 52. 62.]
 [73. 83. 93.]]


In [8]:
# 5. Handling Incompatible Shape Scenario Gracefully**
tensorA = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensorB = tf.constant([5, 6, 7], dtype=tf.float32)

In [9]:
try:
    result = tf.add(tensorA, tensorB)
    print("Result:\n", result.numpy())
except tf.errors.InvalidArgumentError as e:
    print("Error: Tensors have incompatible shapes for broadcasting.")

Error: Tensors have incompatible shapes for broadcasting.


---

### **Explanation**
1. **Scalar Broadcasting**: The scalar `5.0` was broadcasted to the shape `(2, 2)` to match the tensor.
2. **Row Vector Broadcasting**: The row vector `[2, 3, 4]` was expanded to the shape `(2, 3)` to match the tensor.
3. **Column Vector Broadcasting**: The column vector `[[1], [2], [3]]` was expanded to `(3, 3)` to match the tensor.
4. **Error Handling**: The incompatible shapes `(2, 2)` and `(3,)` caused a broadcasting error, which was caught and displayed as a custom message.

---

### **Time Complexity Analysis**
- **Element-wise operations (`tf.add`, `tf.multiply`)** → **O(n)** where `n` is the number of elements.
- **Broadcasting** is typically **O(1)** as it is handled at the **metadata level**, avoiding deep copies of data.
- **Error Handling** adds a **minimal overhead**, mainly related to exception catching.

---

---
# Additional Explanation

### **What is Broadcasting in TensorFlow?**
Broadcasting is a **powerful feature in TensorFlow** (and NumPy) that allows arithmetic operations on **tensors of different shapes** by **automatically expanding** the smaller tensor to match the dimensions of the larger tensor. This eliminates the need for explicit dimension matching and makes computations more efficient.

---

### **Why is Broadcasting Useful?**
- It **avoids unnecessary memory allocation** for repeated values.
- It **allows operations on different-shaped tensors** without manually reshaping them.
- It is **optimized for performance** in TensorFlow and NumPy.

---

### **Broadcasting Rules**
When performing operations between two tensors of different shapes, TensorFlow follows these rules:

1. **If the dimensions of the two tensors are different, TensorFlow will try to match them from right to left.**
2. **If a dimension in one tensor is `1`, it will be stretched (broadcasted) to match the corresponding dimension of the larger tensor.**
3. **If the dimensions do not match and neither is `1`, TensorFlow will throw an error.**

---

### **Examples of Broadcasting**

#### **Example 1: Broadcasting a Scalar to a Tensor**
A scalar (single number) is broadcasted to match a matrix.

##### **Code**
```python
import tensorflow as tf

tensor = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
scalar = tf.constant(2.0, dtype=tf.float32)

# TensorFlow automatically expands the scalar to match the tensor shape
result = tensor * scalar

print("Original Tensor:\n", tensor.numpy())
print("Scalar:\n", scalar.numpy())
print("Broadcasted Multiplication Result:\n", result.numpy())
```
##### **Output**
```
Original Tensor:
[[1. 2.]
 [3. 4.]]

Scalar:
2.0

Broadcasted Multiplication Result:
[[ 2.  4.]
 [ 6.  8.]]
```
✔️ The **scalar `2.0` is automatically broadcasted** to `[[2. 2.], [2. 2.]]` to match the tensor's shape.

---

#### **Example 2: Broadcasting a 1D Vector to a 2D Matrix**
A **row vector** is broadcasted to match a **2D matrix**.

##### **Code**
```python
matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
vector = tf.constant([1, 2, 3], dtype=tf.float32)

# Broadcasting the 1D vector to match the 2D matrix
result = matrix + vector

print("Original Matrix:\n", matrix.numpy())
print("Vector:\n", vector.numpy())
print("Broadcasted Addition Result:\n", result.numpy())
```
##### **Output**
```
Original Matrix:
[[1. 2. 3.]
 [4. 5. 6.]]

Vector:
[1. 2. 3.]

Broadcasted Addition Result:
[[ 2.  4.  6.]
 [ 5.  7.  9.]]
```
✔️ The **1D vector `[1, 2, 3]` is broadcasted** to `[[1, 2, 3], [1, 2, 3]]` to match the matrix shape.

---

#### **Example 3: Broadcasting a Column Vector to a Matrix**
A **column vector** (shape `(3,1)`) is broadcasted to match a **2D matrix**.

##### **Code**
```python
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
column_vector = tf.constant([[1], [2], [3]], dtype=tf.float32)

# Broadcasting the column vector to match the matrix
result = matrix + column_vector

print("Original Matrix:\n", matrix.numpy())
print("Column Vector:\n", column_vector.numpy())
print("Broadcasted Addition Result:\n", result.numpy())
```
##### **Output**
```
Original Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Column Vector:
[[1.]
 [2.]
 [3.]]

Broadcasted Addition Result:
[[ 2.  3.  4.]
 [ 6.  7.  8.]
 [10. 11. 12.]]
```
✔️ The **column vector `[[1], [2], [3]]` is broadcasted** to `[[1, 1, 1], [2, 2, 2], [3, 3, 3]]` to match the matrix shape.

---

### **When Does Broadcasting Fail?**
If two tensors have **incompatible shapes** that cannot be expanded to match, TensorFlow will throw an error.

##### **Example of an Incompatible Shape**
```python
tensorA = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensorB = tf.constant([5, 6, 7], dtype=tf.float32)  # Shape (3,)

# This will throw an error because the shapes are incompatible
result = tensorA + tensorB  
```
##### **Error**
```
InvalidArgumentError: Incompatible shapes: [2,2] vs. [3]
```
✔️ **Why?** `tensorA` has shape **(2,2)** but `tensorB` has shape **(3,)**, which **cannot** be broadcasted.

---

### **Final Summary**
| Scenario | Example | Broadcasting Works? |
|----------|---------|--------------------|
| Scalar to Tensor | `[[1, 2], [3, 4]] + 2.0` | ✅ Yes |
| Row Vector to Matrix | `[[1, 2, 3], [4, 5, 6]] + [1, 2, 3]` | ✅ Yes |
| Column Vector to Matrix | `[[1, 2, 3], [4, 5, 6]] + [[1], [2], [3]]` | ✅ Yes |
| Mismatched Shapes | `[[1, 2], [3, 4]] + [5, 6, 7]` | ❌ No |

---

### **Key Takeaways**
- **Broadcasting lets you perform operations on different-shaped tensors without explicitly reshaping them.**
- **If a tensor has `1` in a dimension, it can be expanded to match another tensor’s shape.**
- **If dimensions do not match and neither is `1`, TensorFlow will throw an error.**
- **Broadcasting makes tensor operations more efficient and memory-friendly.**

Let me know if you need further clarification! 🚀