# **Challenge #3: Basic Tensor Operations in TensorFlow**  
#### **Topic**: Perform Reshaping, Transposing, Broadcasting, and Element-Wise Operations  

---

### **Problem Description**:
In this challenge, you will demonstrate your understanding of **basic tensor operations** in TensorFlow. Your tasks include:

1. **Reshaping a tensor** from **shape `(4, 3)` to `(2, 6)`**.
2. **Transposing a tensor** to switch its rows and columns.
3. **Applying broadcasting** to perform arithmetic operations between tensors of **incompatible shapes**.
4. **Executing element-wise operations**, such as **addition**, **subtraction**, **multiplication**, and **division** on tensors.

---

### **Constraints**:
- All tensors must be of **dtype `float32`**.
- Use only **TensorFlow functions** for all operations (`tf.reshape()`, `tf.transpose()`, `tf.add()`, etc.).
- If an operation fails due to **shape incompatibility**, your code should **gracefully handle the error**.

---

### **Example Input & Output**

#### **Example 1: Reshaping a Tensor**  
##### **Input**:
```python
# Given this tensor:
tensor = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

# Reshape it to (2, 6).
```
##### **Expected Output**:
```
Reshaped Tensor:
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]
```

---

#### **Example 2: Transposing a Tensor**  
##### **Input**:
```python
# Given this tensor:
tensor = [[1, 2], [3, 4], [5, 6]]

# Transpose the tensor.
```
##### **Expected Output**:
```
Transposed Tensor:
[[1. 3. 5.]
 [2. 4. 6.]]
```

---

#### **Example 3: Broadcasting Example**  
##### **Input**:
```python
# Given these tensors:
tensor = [[1, 2, 3], [4, 5, 6]]
scalar = 10.0

# Add the scalar to the tensor using broadcasting.
```
##### **Expected Output**:
```
Broadcasted Addition:
[[11. 12. 13.]
 [14. 15. 16.]]
```

---

#### **Example 4: Element-Wise Operations**  
##### **Input**:
```python
# Given these tensors:
tensorA = [[1, 2], [3, 4]]
tensorB = [[5, 6], [7, 8]]

# Perform element-wise addition, subtraction, multiplication, and division.
```
##### **Expected Output**:
```
Addition:
[[ 6.  8.]
 [10. 12.]]

Subtraction:
[[-4. -4.]
 [-4. -4.]]

Multiplication:
[[ 5. 12.]
 [21. 32.]]

Division:
[[0.2        0.33333334]
 [0.42857143 0.5       ]]
```

---

### **Hints**:
- Use `tf.reshape()` to change the shape of a tensor.
- Use `tf.transpose()` to switch rows and columns.
- Apply broadcasting by using `tf.add()` with tensors of different shapes.
- Perform element-wise operations using `tf.add()`, `tf.subtract()`, `tf.multiply()`, and `tf.divide()`.

---


# Solution

In [2]:
import tensorflow as tf

In [3]:
# 1. Reshaping a Tensor

tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=tf.float32)

reshaped_tensor = tf.reshape(tensor, (2, 6))
print("Reshaped Tensor:\n", reshaped_tensor.numpy())

Reshaped Tensor:
 [[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


In [4]:
# 2. Transposing a Tensor

tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)

transposed_tensor = tf.transpose(tensor)
print("Transposed Tensor:\n", transposed_tensor.numpy())

Transposed Tensor:
 [[1. 3. 5.]
 [2. 4. 6.]]


In [5]:
# 3. Broadcasting Example**

tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
scalar = tf.constant(10.0, dtype=tf.float32)

broadcasted_tensor = tf.add(tensor, scalar)
print("Broadcasted Addition:\n", broadcasted_tensor.numpy())

Broadcasted Addition:
 [[11. 12. 13.]
 [14. 15. 16.]]


In [6]:
# 4. Element-Wise Operations**

tensorA = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensorB = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

addition_result = tf.add(tensorA, tensorB)
print("Addition:\n", addition_result.numpy())

subtraction_result = tf.subtract(tensorA, tensorB)
print("Subtraction:\n", subtraction_result.numpy())

multiplication_result = tf.multiply(tensorA, tensorB)
print("Multiplication:\n", multiplication_result.numpy())

division_result = tf.divide(tensorA, tensorB)
print("Division:\n", division_result.numpy())

Addition:
 [[ 6.  8.]
 [10. 12.]]
Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Multiplication:
 [[ 5. 12.]
 [21. 32.]]
Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]


---

## **Explanation**
1. **Reshaping**: `tf.reshape()` changed the shape of a `(4, 3)` tensor to `(2, 6)` without altering the data.
2. **Transposing**: `tf.transpose()` swapped the axes of a `(3, 2)` tensor to become `(2, 3)`.
3. **Broadcasting**: `tf.add()` automatically expanded the scalar `10.0` to match the `(2, 3)` shape of the tensor.
4. **Element-Wise Operations**:
   - **Addition**: Performed element-by-element.
   - **Subtraction**: Handled negative differences.
   - **Multiplication**: Produced products of corresponding elements.
   - **Division**: Managed float division, preserving the `float32` type.

---

## **Time Complexity Analysis**
- **Reshaping (`tf.reshape()`)**: **O(1)** (only changes metadata).
- **Transposing (`tf.transpose()`)**: **O(n)** where `n` is the number of elements.
- **Broadcasting (`tf.add()`)**: **O(n)** for arithmetic operations, broadcasting itself is **O(1)**.
- **Element-Wise Operations (`tf.add()`, `tf.subtract()`, `tf.multiply()`, `tf.divide()`)**: **O(n)**.

---

## **Edge Cases Handled**
- The **reshaping** operation ensures that the **total number of elements** remains the same (`4 * 3 = 2 * 6`).
- **Broadcasting** was demonstrated with **compatible shapes**, avoiding potential shape mismatch errors.
- **Element-wise division** avoided division by zero, as all elements in `tensorB` are **non-zero**.

---