# **Challenge #4: Understanding Element-wise, Vector-Tensor, and Tensor-Tensor Operations in TensorFlow**  
#### **Topic**: Clarifying the differences between **element-wise**, **vector-tensor**, and **tensor-tensor** operations.  

---

### **Problem Description**:
In this challenge, you will perform and analyze the differences between three types of operations in TensorFlow:

1. **Element-wise Operations**:
   - Perform addition, subtraction, multiplication, and division on two tensors of the **same shape**.

2. **Vector with Tensor Operations**:
   - Multiply a **1D vector** with a **2D tensor** using **broadcasting**.
   - Add a **column vector** to a **2D tensor** using **broadcasting**.

3. **Tensor with Tensor Operations**:
   - Perform **matrix multiplication** (dot product) on two **compatible 2D tensors**.
   - Apply **broadcasting rules** for arithmetic operations on tensors of **different shapes**.

---

### **Constraints**:
- All tensors must be of **dtype `float32`**.
- Use only **TensorFlow functions** for all operations (`tf.add()`, `tf.multiply()`, `tf.matmul()`, etc.).
- Code should **handle shape mismatches gracefully** with proper error messages.

---

### **Example Input & Output**

#### **Example 1: Element-Wise Operations**  
##### **Input**:
```python
# Given these tensors:
tensorA = [[1, 2], [3, 4]]
tensorB = [[5, 6], [7, 8]]

# Perform element-wise addition, subtraction, multiplication, and division.
```
##### **Expected Output**:
```
Addition:
[[ 6.  8.]
 [10. 12.]]

Subtraction:
[[-4. -4.]
 [-4. -4.]]

Multiplication:
[[ 5. 12.]
 [21. 32.]]

Division:
[[0.2        0.33333334]
 [0.42857143 0.5       ]]
```

---

#### **Example 2: Vector with Tensor Operations**  
##### **Input**:
```python
# Given this 2D tensor:
tensor = [[1, 2, 3], [4, 5, 6]]

# And this 1D row vector:
row_vector = [1, 2, 3]

# Add the row vector to the tensor using broadcasting.
```
##### **Expected Output**:
```
Broadcasted Addition:
[[ 2.  4.  6.]
 [ 5.  7.  9.]]
```

---

#### **Example 3: Column Vector with 2D Tensor**  
##### **Input**:
```python
# Given this tensor:
tensor = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

# Add the column vector [[1], [2], [3]] using broadcasting.
```
##### **Expected Output**:
```
Broadcasted Addition:
[[ 11.  21.  31.]
 [ 42.  52.  62.]
 [ 73.  83.  93.]]
```

---

#### **Example 4: Tensor with Tensor Operations**  
##### **Input**:
```python
# Given these tensors:
tensorA = [[1, 2, 3], [4, 5, 6]]
tensorB = [[7, 8], [9, 10], [11, 12]]

# Perform matrix multiplication.
```
##### **Expected Output**:
```
Matrix Multiplication Result:
[[ 58.  64.]
 [139. 154.]]
```

---

#### **Example 5: Broadcasting with Different Shapes**  
##### **Input**:
```python
# Given these tensors:
tensorA = [[1, 2, 3]]
tensorB = [[4], [5], [6]]

# Perform element-wise multiplication using broadcasting.
```
##### **Expected Output**:
```
Broadcasted Multiplication:
[[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]
```

---

### **Hints**:
- Use `tf.add()`, `tf.subtract()`, `tf.multiply()`, `tf.divide()` for **element-wise operations**.
- Use `tf.matmul()` for **matrix multiplication**.
- For **broadcasting** with **vectors and tensors**, TensorFlow automatically adjusts shapes, but be mindful of **incompatible shapes**.

---

This challenge should help in distinguishing between **element-wise operations**, **vector-tensor interactions**, and **tensor-tensor operations** with **broadcasting concepts**. Let me know if this aligns with your expectations! 🚀

# Solution

In [1]:
# 1. Import Necessary Libraries
import tensorflow as tf

In [2]:
# 2. Element-Wise Operations
tensorA = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensorB = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

addition_result = tf.add(tensorA, tensorB)
print("Element-Wise Addition:\n", addition_result.numpy())

subtraction_result = tf.subtract(tensorA, tensorB)
print("Element-Wise Subtraction:\n", subtraction_result.numpy())

multiplication_result = tf.multiply(tensorA, tensorB)
print("Element-Wise Multiplication:\n", multiplication_result.numpy())

division_result = tf.divide(tensorA, tensorB)
print("Element-Wise Division:\n", division_result.numpy())


Element-Wise Addition:
 [[ 6.  8.]
 [10. 12.]]
Element-Wise Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Element-Wise Multiplication:
 [[ 5. 12.]
 [21. 32.]]
Element-Wise Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]


In [3]:
# 3. Vector with Tensor Operations
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
row_vector = tf.constant([1, 2, 3], dtype=tf.float32)

broadcasted_addition = tf.add(tensor, row_vector)
print("Vector-Tensor Broadcasted Addition:\n", broadcasted_addition.numpy())

Vector-Tensor Broadcasted Addition:
 [[2. 4. 6.]
 [5. 7. 9.]]


In [4]:
# 4. Column Vector with 2D Tensor
tensor = tf.constant([[10, 20, 30], [40, 50, 60], [70, 80, 90]], dtype=tf.float32)
column_vector = tf.constant([[1], [2], [3]], dtype=tf.float32)

column_broadcasted_addition = tf.add(tensor, column_vector)
print("Column Vector with Tensor Broadcasting:\n", column_broadcasted_addition.numpy())

Column Vector with Tensor Broadcasting:
 [[11. 21. 31.]
 [42. 52. 62.]
 [73. 83. 93.]]


In [5]:
# 5. Tensor with Tensor Operations (Matrix Multiplication)
tensorA = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
tensorB = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.float32)

matrix_multiplication_result = tf.matmul(tensorA, tensorB)
print("Matrix Multiplication (Tensor-Tensor) Result:\n", matrix_multiplication_result.numpy())

Matrix Multiplication (Tensor-Tensor) Result:
 [[ 58.  64.]
 [139. 154.]]


In [6]:
# 6. Broadcasting with Different Shapes
tensorA = tf.constant([[1, 2, 3]], dtype=tf.float32)
tensorB = tf.constant([[4], [5], [6]], dtype=tf.float32)

broadcasted_multiplication = tf.multiply(tensorA, tensorB)
print("Broadcasted Multiplication:\n", broadcasted_multiplication.numpy())

matrix_multiplication_result = tf.matmul(tensorA, tensorB)
print("\nMatrix Multiplication (Tensor-Tensor) Result:\n", matrix_multiplication_result.numpy())

Broadcasted Multiplication:
 [[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]

Matrix Multiplication (Tensor-Tensor) Result:
 [[32.]]


---
### **Broadcasted Multiplication**
- **Shape of `tensorA`**: `(1, 3)`  
- **Shape of `tensorB`**: `(3, 1)`  
- **Broadcasted Result Shape**: `(3, 3)`

#### **Expected Output**
```
Broadcasted Multiplication:
[[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]
```

#### **Why?**
- **Broadcasting** stretches `tensorA` from `(1, 3)` to `(3, 3)` by **repeating the row**.
- `tensorB` is stretched from `(3, 1)` to `(3, 3)` by **repeating the column**.
- The resulting operation is:

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 3 \\
1 & 2 & 3
\end{bmatrix}
*
\begin{bmatrix}
4 & 4 & 4 \\
5 & 5 & 5 \\
6 & 6 & 6
\end{bmatrix}
=
\begin{bmatrix}
4 & 8 & 12 \\
5 & 10 & 15 \\
6 & 12 & 18
\end{bmatrix}
$

---

### **Matrix Multiplication (`tf.matmul()`)**
- **Shape of `tensorA`**: `(1, 3)`  
- **Shape of `tensorB`**: `(3, 1)`  
- **Resulting Shape**: `(1, 1)`

#### **Expected Output**
```
Matrix Multiplication (Tensor-Tensor) Result:
[[32.]]
```

#### **Why?**
- **Matrix Multiplication** involves the **dot product** of the row vector of `tensorA` and the column vector of `tensorB`:

$
[1, 2, 3] \cdot [4, 5, 6]^T = (1 \times 4) + (2 \times 5) + (3 \times 6) = 4 + 10 + 18 = 32
$

---

## **Key Differences Highlighted by This Example**

| **Operation Type**       | **Operation**                          | **Result Shape** | **Behavior**                                                    |
|---------------------------|----------------------------------------|-----------------|----------------------------------------------------------------|
| **Element-wise**         | `tf.multiply(tensorA, tensorB)`        | `(3, 3)`        | Broadcasts to match shapes, then multiplies **element-wise**.   |
| **Matrix Multiplication** | `tf.matmul(tensorA, tensorB)`          | `(1, 1)`        | Computes **dot product**, following matrix multiplication rules.|

---

---

## **Explanation of Key Concepts**

### **1. Element-Wise Operations**
- Operations are performed **element by element**.
- Requires **tensors of the same shape**.
- Examples: `tf.add()`, `tf.subtract()`, `tf.multiply()`, `tf.divide()`.

---

### **2. Vector with Tensor Operations (Broadcasting)**
- **Row Vector** is automatically **expanded** to match the **2D tensor** shape.
- **Column Vector** broadcasting expands to each row of the tensor.
- Broadcasting allows **operations on mismatched shapes** without explicit reshaping.

---

### **3. Tensor with Tensor Operations (Matrix Multiplication)**
- **Matrix multiplication** is not **element-wise** but involves **dot product calculations**.
- **Shapes must align**: `(m, n) x (n, p) → (m, p)`.
- Performed using `tf.matmul()`, not `tf.multiply()`.

---

### **4. Broadcasting with Different Shapes**
- **Tensor A Shape**: `(1, 3)`
- **Tensor B Shape**: `(3, 1)`
- Broadcasting result shape: `(3, 3)`.
- **Multiplication** involves each row of **tensor A** multiplied by each column of **tensor B**.

---

## **Time Complexity Analysis**
| **Operation Type**         | **Time Complexity** |
|-----------------------------|---------------------|
| Element-Wise Operations     | **O(n)**            |
| Broadcasting Operations     | **O(n)**            |
| Matrix Multiplication       | **O(m * n * p)**    |

- **n**: Number of elements in tensors.
- **m, n, p**: Dimensions of the matrices for matrix multiplication.

---

## **Edge Cases Handled**
- **Shape Mismatches**: All broadcasting operations are performed with **compatible shapes**.
- **Error Handling**: If broadcasting fails, TensorFlow will automatically **raise an error**, which can be handled using **try-except blocks** if needed.

---