# **Challenge #5: Interoperability Between TensorFlow Tensors and NumPy Arrays**  
#### **Topic**: Convert Between **TensorFlow Tensors** and **NumPy Arrays**

---

### **Problem Description**:
In this challenge, you will demonstrate how to seamlessly **convert data** between **TensorFlow tensors** and **NumPy arrays**. Your tasks include:

1. **Convert a NumPy array to a TensorFlow tensor** using **`tf.convert_to_tensor()`**.
2. **Create a tensor using TensorFlow** and convert it to a **NumPy array** using **`.numpy()`**.
3. **Perform arithmetic operations** on the tensor and ensure the result can be converted back to a **NumPy array**.
4. Verify that **changes to the original NumPy array** do not affect the **TensorFlow tensor** (and vice versa).

---

### **Constraints**:
- Use only **TensorFlow** and **NumPy** functions (`tf.convert_to_tensor()`, `.numpy()`, `np.array()`, etc.).
- Ensure all **tensors** are of **dtype `float32`**.
- Properly **handle edge cases** where conversion might result in **data type mismatch**.

---

### **Example Input & Output**

#### **Example 1: Convert NumPy Array to TensorFlow Tensor**  
##### **Input**:
```python
# Given this NumPy array:
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

# Convert it to a TensorFlow tensor.
```
##### **Expected Output**:
```
Tensor:
[[1. 2. 3.]
 [4. 5. 6.]]
Data Type: <dtype: 'float32'>
```

---

#### **Example 2: Convert TensorFlow Tensor to NumPy Array**  
##### **Input**:
```python
# Given this TensorFlow tensor:
import tensorflow as tf
tensor = tf.constant([[10.0, 20.0], [30.0, 40.0]], dtype=tf.float32)

# Convert it to a NumPy array.
```
##### **Expected Output**:
```
NumPy Array:
[[10. 20.]
 [30. 40.]]
Data Type: float32
```

---

#### **Example 3: Arithmetic Operations and Conversion**  
##### **Input**:
```python
# Given these tensors:
tensorA = tf.constant([1, 2, 3], dtype=tf.float32)
tensorB = tf.constant([4, 5, 6], dtype=tf.float32)

# Perform element-wise addition and convert the result to a NumPy array.
```
##### **Expected Output**:
```
Resulting NumPy Array:
[5. 7. 9.]
Data Type: float32
```

---

#### **Example 4: Independent Memory Allocation**  
##### **Input**:
```python
# Given this NumPy array:
np_array = np.array([10, 20, 30], dtype=np.float32)

# Convert it to a TensorFlow tensor and modify the original NumPy array.
```
##### **Expected Output**:
```
Modified NumPy Array:
[100. 200. 300.]

Tensor Remains Unchanged:
[10. 20. 30.]
```

---

### **Hints**:
- Use **`.numpy()`** to convert a **TensorFlow tensor** to a **NumPy array**.
- Use **`tf.convert_to_tensor()`** to convert a **NumPy array** to a **TensorFlow tensor**.
- Ensure the **data type remains consistent** (`float32`) during conversions.

---

This challenge will solidify your understanding of how **TensorFlow and NumPy** can work together, especially in **preprocessing data**, **model input/output**, and **data analysis**. Let me know if this aligns with your expectations! 🚀

# Solution

In [1]:
# Import Necessary Libraries
import tensorflow as tf
import numpy as np

In [2]:
# 1. Convert NumPy Array to TensorFlow Tensor
np_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

tensor_from_np = tf.convert_to_tensor(np_array)
print("Converted Tensor from NumPy Array:\n", tensor_from_np)
print("Data Type:", tensor_from_np.dtype)

Converted Tensor from NumPy Array:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Data Type: <dtype: 'float32'>


In [3]:
# 2. Convert TensorFlow Tensor to NumPy Array
tensor = tf.constant([[10.0, 20.0], [30.0, 40.0]], dtype=tf.float32)

np_array_from_tensor = tensor.numpy()
print("Converted NumPy Array from Tensor:\n", np_array_from_tensor)
print("Data Type:", np_array_from_tensor.dtype)

Converted NumPy Array from Tensor:
 [[10. 20.]
 [30. 40.]]
Data Type: float32


In [4]:
# 3. Performing Arithmetic Operations and Conversion
tensorA = tf.constant([1, 2, 3], dtype=tf.float32)
tensorB = tf.constant([4, 5, 6], dtype=tf.float32)

# Element-Wise Addition and Conversion to NumPy
result_tensor = tf.add(tensorA, tensorB)
result_np_array = result_tensor.numpy()

print("Resulting NumPy Array from Element-Wise Addition:\n", result_np_array)
print("Data Type:", result_np_array.dtype)

Resulting NumPy Array from Element-Wise Addition:
 [5. 7. 9.]
Data Type: float32


In [5]:
# 4. Independent Memory Allocation Between Tensor and NumPy Array
np_array = np.array([10, 20, 30], dtype=np.float32)

# Convert and Modify Original Array
tensor_from_np = tf.convert_to_tensor(np_array)

# Modify the original NumPy array
np_array *= 100
tensor_from_np *= 10

print("Modified NumPy Array:\n", np_array)
print("Modified Tensor:\n", tensor_from_np.numpy())

Modified NumPy Array:
 [1000. 2000. 3000.]
Modified Tensor:
 [100. 200. 300.]


---

## **Explanation of Key Concepts**

### **1. Conversion: NumPy to TensorFlow**
- **Function Used**: `tf.convert_to_tensor()`
- The conversion is **copy-based**, meaning the original **NumPy array** and the resulting **TensorFlow tensor** are **independent**.

---

### **2. Conversion: TensorFlow to NumPy**
- **Method Used**: `.numpy()`
- Converts the **tensor** to a **NumPy array**, maintaining **data type** and **shape**.
- The conversion is **efficient** and commonly used in **model evaluation** and **data preprocessing**.

---

### **3. Memory Independence**
- Modifying the **original NumPy array** does **not affect** the **TensorFlow tensor** created from it.
- This ensures **safe data handling** when tensors are used in **computational graphs** or **deep learning models**.

---

### **4. Edge Cases Handled**
- **Data Type Consistency**: Ensured that all conversions maintain the **`float32`** type.
- **Shape Compatibility**: The shapes remain consistent before and after conversion.

---

## **Time Complexity Analysis**
| **Operation**                          | **Time Complexity** |
|---------------------------------------|---------------------|
| Conversion (NumPy → TensorFlow)        | **O(n)**            |
| Conversion (TensorFlow → NumPy)        | **O(n)**            |
| Element-Wise Operations (`tf.add()`)   | **O(n)**            |

- **n**: Number of elements in the tensor/array.

---